server:
  port: 8081
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:users_management}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:bass}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,refresh
    endpoint:
      health:
        show-details: always

  logging:
    level:
      dev.edgeahz.ec.sports.authsrver: DEBUG
      org.springdoc: DEBUG
      org.springframework.web: INFO
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: DEBUG

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    packages-to-scan: dev.edgeahz.ec.spstore.user_management.api.rest
